package resolver

var NodeBuiltin = map[string]bool{
	"assert":        true,
	"assert/strict": true,

	"dns":          true,
	"dns/promises": true,

	"fs":         true,
	"fs/promise": true,

	"stream":           true,
	"stream/consumers": true,
	"stream/promises":  true,
	"stream/web":       true,

	"timers":          true,
	"timers/promises": true,

	"async_hooks":         true,
	"buffer":              true,
	"child_process":       true,
	"cluster":             true,
	"console":             true,
	"constants":           true,
	"crypto":              true,
	"dgram":               true,
	"diagnostics_channel": true,
	"domain":              true,
	"events":              true,
	"http":                true,
	"http2":               true,
	"https":               true,
	"inspector":           true,
	"module":              true,
	"net":                 true,
	"os":                  true,

	"path":       true,
	"path/posix": true,
	"path/win32": true,

	"perf_hooks":     true,
	"process":        true,
	"punycode":       true,
	"querystring":    true,
	"readline":       true,
	"repl":           true,
	"string_decoder": true,
	"trace_events":   true,
	"tty":            true,
	"url":            true,
	"util":           true,
	"util/types":     true,
	"v8":             true,
	"vm":             true,
	"wasi":           true,
	"worker_threads": true,
	"zlib":           true,
}

// refer: https://github.com/facebook/metro/blob/main/packages/metro-react-native-babel-preset/src/configs/lazy-imports.js
var RnBuiltin = map[string]bool{
	"AccessibilityInfo":        true,
	"ActivityIndicator":        true,
	"Button":                   true,
	"DatePickerIOS":            true,
	"DrawerLayoutAndroid":      true,
	"FlatList":                 true,
	"Image":                    true,
	"ImageBackground":          true,
	"InputAccessoryView":       true,
	"KeyboardAvoidingView":     true,
	"MaskedViewIOS":            true,
	"Modal":                    true,
	"Pressable":                true,
	"ProgressBarAndroid":       true,
	"ProgressViewIOS":          true,
	"SafeAreaView":             true,
	"ScrollView":               true,
	"SectionList":              true,
	"Slider":                   true,
	"Switch":                   true,
	"RefreshControl":           true,
	"StatusBar":                true,
	"Text":                     true,
	"TextInput":                true,
	"Touchable":                true,
	"TouchableHighlight":       true,
	"TouchableNativeFeedback":  true,
	"TouchableOpacity":         true,
	"TouchableWithoutFeedback": true,
	"View":                     true,
	"VirtualizedList":          true,
	"VirtualizedSectionList":   true,

	"ReactNativeART":      true,
	"warnOnce":            true,
	"TurboModuleRegistry": true,
	"TimePickerAndroid":   true,

	// APIs
	"ActionSheetIOS":      true,
	"Alert":               true,
	"Animated":            true,
	"Appearance":          true,
	"AppRegistry":         true,
	"AppState":            true,
	"AsyncStorage":        true,
	"BackHandler":         true,
	"Clipboard":           true,
	"DeviceInfo":          true,
	"Dimensions":          true,
	"Easing":              true,
	"ReactNative":         true,
	"I18nManager":         true,
	"InteractionManager":  true,
	"Keyboard":            true,
	"LayoutAnimation":     true,
	"Linking":             true,
	"LogBox":              true,
	"NativeEventEmitter":  true,
	"PanResponder":        true,
	"PermissionsAndroid":  true,
	"PixelRatio":          true,
	"PushNotificationIOS": true,
	"Settings":            true,
	"Share":               true,
	"StyleSheet":          true,
	"Systrace":            true,
	"ToastAndroid":        true,
	"TVEventHandler":      true,
	"UIManager":           true,
	"UTFSequence":         true,
	"Vibration":           true,

	// Plugins
	"RCTDeviceEventEmitter":    true,
	"RCTNativeAppEventEmitter": true,
	"NativeModules":            true,
	"Platform":                 true,
	"processColor":             true,
	"requireNativeComponent":   true,

	// deprecated
	"YellowBox":                    true,
	"DeprecatedViewPropTypes":      true,
	"DeprecatedEdgeInsetsPropType": true,
	"DeprecatedPointPropType":      true,
	"DeprecatedColorPropType":      true,
	"StatusBarIOS":                 true,
	"ViewPagerAndroid":             true,
	"CheckBox":                     true,
	"ImageStore":                   true,
	"PickerIOS":                    true,
	"ImageEditor":                  true,
	"Picker":                       true,
	"SegmentedControlIOS":          true,
	"ToolbarAndroid":               true,
	"CameraRoll":                   true,
	"DatePickerAndroid":            true,
	"ImagePickerIOS":               true,

	"dismissKeyboard": true,
}
