on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.2]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Prepare git
      run: |-
        git config --global core.autocrlf false
        git config --global core.eol lf

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup node@16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Test
      run: make test